# Ghosttyhaus — Thinkinghaus palette v0.4
# https://keeping.haus/thinkinghaus-palette/
# Window
window-padding-x = 20
window-padding-y = 20

# Typography (Paper Mono is installed separately)
font-family = "Paper Mono"
font-size = 15
adjust-cell-height = 10%

# neutral-1000 / neutral-0
background = #1A1814
foreground = #F1EDE3

# neutral-850
palette = 0=#38352E

# clay-solid
palette = 1=#99422D

# moss-solid
palette = 2=#506436

# ochre-solid
palette = 3=#735A23

# slate-600
palette = 4=#416084

# heather-600
palette = 5=#735379

# patina-solid
palette = 6=#386560

# neutral-400
palette = 7=#ADADAA

# neutral-700
palette = 8=#605B51

# clay-400
palette = 9=#D08471

# moss-400
palette = 10=#94AA79

# ochre-400
palette = 11=#B59249

# slate-400
palette = 12=#89A3C4

# heather-400
palette = 13=#B296B7

# patina-400
palette = 14=#72AEA6

# neutral-0
palette = 15=#F1EDE3

# neutral-700
selection-background = #605B51

# neutral-0
selection-foreground = #F1EDE3

# clay-400
cursor-color = #D08471

# neutral-1000
cursor-text = #1A1814
