# Ghosttyhaus — Thinkinghaus palette v0.5
# https://keeping.haus/thinkinghaus-palette/
# Window
window-padding-x = 20
window-padding-y = 20

# Typography (Paper Mono is installed separately)
font-family = "Paper Mono"
font-size = 15
adjust-cell-height = 10%

# neutral-1000 / neutral-0
background = #1C1811
foreground = #F4EDDF

# neutral-850
palette = 0=#3A352A

# clay-solid
palette = 1=#9B4127

# moss-solid
palette = 2=#536431

# ochre-solid
palette = 3=#75591C

# slate-600
palette = 4=#446081

# heather-600
palette = 5=#755376

# patina-solid
palette = 6=#3B655C

# neutral-400
palette = 7=#AFADA6

# neutral-700
palette = 8=#625B4D

# clay-400
palette = 9=#D2836C

# moss-400
palette = 10=#97AA74

# ochre-400
palette = 11=#B79142

# slate-400
palette = 12=#8CA3C0

# heather-400
palette = 13=#B496B3

# patina-400
palette = 14=#75AEA2

# neutral-0
palette = 15=#F4EDDF

# neutral-700
selection-background = #625B4D

# neutral-0
selection-foreground = #F4EDDF

# clay-400
cursor-color = #D2836C

# neutral-1000
cursor-text = #1C1811
